name: CreateRelease

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true

jobs:
  Create-Release:
    runs-on: ubuntu-latest
    steps:
    - name: DownloadArtifact
      uses: actions/download-artifact@v4
      with:
        merge-multiple: true

    - name: CrateRelease
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ inputs.tag }}
        tag_name: ${{ inputs.tag }}
        prerelease: ${{ contains(inputs.tag,'-') }}
        generate_release_notes: true
        files: |
          tex-trans-core-${{ inputs.tag }}.zip
          package.json
