name: CreateTTCNewVersionAndRelease

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true

jobs:
  UpdateTTC:
    uses: ./.github/workflows/UpdateTTC.yml
    with:
      tag: ${{ inputs.tag }}

  CreateZip:
    uses: ./.github/workflows/CreateZip.yml
    needs: [UpdateTTC]
    with:
      ref: ${{ inputs.tag }}
  GetPackageJson:
    uses: ./.github/workflows/GetPackageJson.yml
    needs: [UpdateTTC]
    with:
      ref: ${{ inputs.tag }}

  CreateRelease:
    uses: ./.github/workflows/CreateRelease.yml
    needs: [CreateZip, GetPackageJson]
    with:
      tag: ${{ inputs.tag }}

  SendVpmRS64Net:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.VPM_REPO_TOKEN }}
          repository: ReinaS-64892/vpm.rs64.net
          event-type: add_new_version
          client-payload: '{"repository": "TexTransCore", "tag": "${{ inputs.tag }}"}'
